project:
  type: book
  output-dir: docs

book:
  title: "Data Management"
  author: "Anton Urfels"
  date: "3/22/2024"
  sidebar:
    logo: book-code/CGIAR-IRRI.png
  
  chapters:
  - index.qmd
  - part: "Introduction"
    chapters:
    - book-code/intro.qmd
  - part: "Data management workflow"
    chapters:
    - book-code/summary.qmd
  - book-code/references.qmd

bibliography: book-code/references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

