project:
  type: book
  output-dir: docs
 
book:
  title: "Data Management"
  author: "Anton Urfels; Hari S. Nayak"
  date: "3/22/2024"
  sidebar:
    logo: book-code/CGIAR-IRRI.png
  
  chapters:
  - index.qmd
  - part: "Introduction"
    chapters:
    - book-code/intro.qmd
  - part: "Data management workflow"
    chapters:
    - book-code/folder-structure.qmd
  - part: "Course: R for sustainable agriculture"
    chapters:
    - book-code/intro_r_course.qmd
    - training-materials/presentation/intro.qmd
  - book-code/references.qmd

bibliography: book-code/references.bib

format:
  html:
    theme: cosmo

editor: visual

